---
- hosts: all
  become: yes
  tasks:
#### conditons
    - name: install a webserver redhat/centos
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == 'RedHat'
    - name: start the service
      service:
         name: httpd
         state: started
      when: ansible_distribution == 'RedHat'
      
    - name: install a webserver on ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == 'Ubuntu'
    - name: start the service
      service:
         name: apache2
         state: started
      when: ansible_distribution == 'Ubuntu'

#    - name: install a webserver Amazon
#      yum:
#        name: httpd
#        state: latest
#      when: ansible_distribution == 'Amazon'

#    - name: install a webserver Amazon
#      service:
#         name: httpd
#         state: started
#      when: ansible_distribution == 'Amazon'
      
#    - name: copy file from here to all servers
#      copy:
#	src: /home/admin/index.php
#	dest: /home/admin/Copy_files/index.php 
#	force: yes


    - name: Copying your php file in the /var/www/html
      copy:
        src: /home/admin/vaish.txt
        dest: /home/admin/vaish.txt
        force: yes
      notify:
          - Install Apache server
          - restart the Apache server

  handlers:
    - name: Install Apache server
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == 'Amazon'

    - name: restart the Apache server
      service:
        name: httpd
        state: started



#    - name: install a Tree
#      yum:
#        name: tree
#        state: latest
#      when: ansible_distribution == 'Amazon'
  
