---
# tasks file for install
- name: install a webserver Amazon
  yum:
     name: httpd
     state: latest
  when: ansible_distribution == 'Amazon'

- name: start the service
  service:
     name: httpd
     state: started
  when: ansible_distribution == 'Amazon'



